services:
  - type: web
    name: pixeo-app
    runtime: docker
    plan: free
    envVars:
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        sync: false
      - key: HOST
        sync: false
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "file:/data/sqlite.db"
    autoDeploy: false
