# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4b7c8adac6d9f4d77510262a0dcb713f"
name = "pixeo"
application_url = "https://pixeo-app.onrender.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_themes,read_themes"

[auth]
redirect_urls = [
  "https://pixeo-app.onrender.com/auth/callback",
  "https://pixeo-app.onrender.com/auth/shopify/callback",
  "https://pixeo-app.onrender.com/api/auth/callback"
]
